/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TerritoryRouteImport } from './routes/territory'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProjetoInteligenteRouteImport } from './routes/projeto-inteligente'
import { Route as MerchandisingRouteImport } from './routes/merchandising'
import { Route as LaunchControlRouteImport } from './routes/launch-control'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as ImportacaoRouteImport } from './routes/importacao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as BaseMestreRouteImport } from './routes/base-mestre'
import { Route as AssetCenterRouteImport } from './routes/asset-center'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LancamentosIndexRouteImport } from './routes/lancamentos.index'
import { Route as BaseMestreIndexRouteImport } from './routes/base-mestre.index'
import { Route as LancamentosIdRouteImport } from './routes/lancamentos.$id'
import { Route as ImportacaoJblRouteImport } from './routes/importacao.jbl'
import { Route as BaseMestreProdutosRouteImport } from './routes/base-mestre.produtos'
import { Route as BaseMestreMateriaisRouteImport } from './routes/base-mestre.materiais'
import { Route as BaseMestreFornecedoresRouteImport } from './routes/base-mestre.fornecedores'
import { Route as BaseMestreFamiliasRouteImport } from './routes/base-mestre.familias'
import { Route as BaseMestreCompatibilidadesRouteImport } from './routes/base-mestre.compatibilidades'
import { Route as BaseMestreCategoriasRouteImport } from './routes/base-mestre.categorias'
import { Route as BaseMestreArquivosRouteImport } from './routes/base-mestre.arquivos'
import { Route as BaseMestreProdutosIndexRouteImport } from './routes/base-mestre.produtos.index'
import { Route as BaseMestreMateriaisIndexRouteImport } from './routes/base-mestre.materiais.index'
import { Route as BaseMestreProdutosNovoRouteImport } from './routes/base-mestre.produtos.novo'
import { Route as BaseMestreProdutosIdRouteImport } from './routes/base-mestre.produtos.$id'
import { Route as BaseMestreMateriaisNovoRouteImport } from './routes/base-mestre.materiais.novo'
import { Route as BaseMestreMateriaisIdRouteImport } from './routes/base-mestre.materiais.$id'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoryRoute = TerritoryRouteImport.update({
  id: '/territory',
  path: '/territory',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoInteligenteRoute = ProjetoInteligenteRouteImport.update({
  id: '/projeto-inteligente',
  path: '/projeto-inteligente',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchandisingRoute = MerchandisingRouteImport.update({
  id: '/merchandising',
  path: '/merchandising',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchControlRoute = LaunchControlRouteImport.update({
  id: '/launch-control',
  path: '/launch-control',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacaoRoute = ImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseMestreRoute = BaseMestreRouteImport.update({
  id: '/base-mestre',
  path: '/base-mestre',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetCenterRoute = AssetCenterRouteImport.update({
  id: '/asset-center',
  path: '/asset-center',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosIndexRoute = LancamentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LancamentosRoute,
} as any)
const BaseMestreIndexRoute = BaseMestreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseMestreRoute,
} as any)
const LancamentosIdRoute = LancamentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LancamentosRoute,
} as any)
const ImportacaoJblRoute = ImportacaoJblRouteImport.update({
  id: '/jbl',
  path: '/jbl',
  getParentRoute: () => ImportacaoRoute,
} as any)
const BaseMestreProdutosRoute = BaseMestreProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => BaseMestreRoute,
} as any)
const BaseMestreMateriaisRoute = BaseMestreMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => BaseMestreRoute,
} as any)
const BaseMestreFornecedoresRoute = BaseMestreFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => BaseMestreRoute,
} as any)
const BaseMestreFamiliasRoute = BaseMestreFamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => BaseMestreRoute,
} as any)
const BaseMestreCompatibilidadesRoute =
  BaseMestreCompatibilidadesRouteImport.update({
    id: '/compatibilidades',
    path: '/compatibilidades',
    getParentRoute: () => BaseMestreRoute,
  } as any)
const BaseMestreCategoriasRoute = BaseMestreCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => BaseMestreRoute,
} as any)
const BaseMestreArquivosRoute = BaseMestreArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => BaseMestreRoute,
} as any)
const BaseMestreProdutosIndexRoute = BaseMestreProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseMestreProdutosRoute,
} as any)
const BaseMestreMateriaisIndexRoute =
  BaseMestreMateriaisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BaseMestreMateriaisRoute,
  } as any)
const BaseMestreProdutosNovoRoute = BaseMestreProdutosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => BaseMestreProdutosRoute,
} as any)
const BaseMestreProdutosIdRoute = BaseMestreProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BaseMestreProdutosRoute,
} as any)
const BaseMestreMateriaisNovoRoute = BaseMestreMateriaisNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => BaseMestreMateriaisRoute,
} as any)
const BaseMestreMateriaisIdRoute = BaseMestreMateriaisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BaseMestreMateriaisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asset-center': typeof AssetCenterRoute
  '/base-mestre': typeof BaseMestreRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/importacao': typeof ImportacaoRouteWithChildren
  '/lancamentos': typeof LancamentosRouteWithChildren
  '/launch-control': typeof LaunchControlRoute
  '/merchandising': typeof MerchandisingRoute
  '/projeto-inteligente': typeof ProjetoInteligenteRoute
  '/relatorios': typeof RelatoriosRoute
  '/territory': typeof TerritoryRoute
  '/usuarios': typeof UsuariosRoute
  '/base-mestre/arquivos': typeof BaseMestreArquivosRoute
  '/base-mestre/categorias': typeof BaseMestreCategoriasRoute
  '/base-mestre/compatibilidades': typeof BaseMestreCompatibilidadesRoute
  '/base-mestre/familias': typeof BaseMestreFamiliasRoute
  '/base-mestre/fornecedores': typeof BaseMestreFornecedoresRoute
  '/base-mestre/materiais': typeof BaseMestreMateriaisRouteWithChildren
  '/base-mestre/produtos': typeof BaseMestreProdutosRouteWithChildren
  '/importacao/jbl': typeof ImportacaoJblRoute
  '/lancamentos/$id': typeof LancamentosIdRoute
  '/base-mestre/': typeof BaseMestreIndexRoute
  '/lancamentos/': typeof LancamentosIndexRoute
  '/base-mestre/materiais/$id': typeof BaseMestreMateriaisIdRoute
  '/base-mestre/materiais/novo': typeof BaseMestreMateriaisNovoRoute
  '/base-mestre/produtos/$id': typeof BaseMestreProdutosIdRoute
  '/base-mestre/produtos/novo': typeof BaseMestreProdutosNovoRoute
  '/base-mestre/materiais/': typeof BaseMestreMateriaisIndexRoute
  '/base-mestre/produtos/': typeof BaseMestreProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asset-center': typeof AssetCenterRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/importacao': typeof ImportacaoRouteWithChildren
  '/launch-control': typeof LaunchControlRoute
  '/merchandising': typeof MerchandisingRoute
  '/projeto-inteligente': typeof ProjetoInteligenteRoute
  '/relatorios': typeof RelatoriosRoute
  '/territory': typeof TerritoryRoute
  '/usuarios': typeof UsuariosRoute
  '/base-mestre/arquivos': typeof BaseMestreArquivosRoute
  '/base-mestre/categorias': typeof BaseMestreCategoriasRoute
  '/base-mestre/compatibilidades': typeof BaseMestreCompatibilidadesRoute
  '/base-mestre/familias': typeof BaseMestreFamiliasRoute
  '/base-mestre/fornecedores': typeof BaseMestreFornecedoresRoute
  '/importacao/jbl': typeof ImportacaoJblRoute
  '/lancamentos/$id': typeof LancamentosIdRoute
  '/base-mestre': typeof BaseMestreIndexRoute
  '/lancamentos': typeof LancamentosIndexRoute
  '/base-mestre/materiais/$id': typeof BaseMestreMateriaisIdRoute
  '/base-mestre/materiais/novo': typeof BaseMestreMateriaisNovoRoute
  '/base-mestre/produtos/$id': typeof BaseMestreProdutosIdRoute
  '/base-mestre/produtos/novo': typeof BaseMestreProdutosNovoRoute
  '/base-mestre/materiais': typeof BaseMestreMateriaisIndexRoute
  '/base-mestre/produtos': typeof BaseMestreProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asset-center': typeof AssetCenterRoute
  '/base-mestre': typeof BaseMestreRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/importacao': typeof ImportacaoRouteWithChildren
  '/lancamentos': typeof LancamentosRouteWithChildren
  '/launch-control': typeof LaunchControlRoute
  '/merchandising': typeof MerchandisingRoute
  '/projeto-inteligente': typeof ProjetoInteligenteRoute
  '/relatorios': typeof RelatoriosRoute
  '/territory': typeof TerritoryRoute
  '/usuarios': typeof UsuariosRoute
  '/base-mestre/arquivos': typeof BaseMestreArquivosRoute
  '/base-mestre/categorias': typeof BaseMestreCategoriasRoute
  '/base-mestre/compatibilidades': typeof BaseMestreCompatibilidadesRoute
  '/base-mestre/familias': typeof BaseMestreFamiliasRoute
  '/base-mestre/fornecedores': typeof BaseMestreFornecedoresRoute
  '/base-mestre/materiais': typeof BaseMestreMateriaisRouteWithChildren
  '/base-mestre/produtos': typeof BaseMestreProdutosRouteWithChildren
  '/importacao/jbl': typeof ImportacaoJblRoute
  '/lancamentos/$id': typeof LancamentosIdRoute
  '/base-mestre/': typeof BaseMestreIndexRoute
  '/lancamentos/': typeof LancamentosIndexRoute
  '/base-mestre/materiais/$id': typeof BaseMestreMateriaisIdRoute
  '/base-mestre/materiais/novo': typeof BaseMestreMateriaisNovoRoute
  '/base-mestre/produtos/$id': typeof BaseMestreProdutosIdRoute
  '/base-mestre/produtos/novo': typeof BaseMestreProdutosNovoRoute
  '/base-mestre/materiais/': typeof BaseMestreMateriaisIndexRoute
  '/base-mestre/produtos/': typeof BaseMestreProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asset-center'
    | '/base-mestre'
    | '/configuracoes'
    | '/importacao'
    | '/lancamentos'
    | '/launch-control'
    | '/merchandising'
    | '/projeto-inteligente'
    | '/relatorios'
    | '/territory'
    | '/usuarios'
    | '/base-mestre/arquivos'
    | '/base-mestre/categorias'
    | '/base-mestre/compatibilidades'
    | '/base-mestre/familias'
    | '/base-mestre/fornecedores'
    | '/base-mestre/materiais'
    | '/base-mestre/produtos'
    | '/importacao/jbl'
    | '/lancamentos/$id'
    | '/base-mestre/'
    | '/lancamentos/'
    | '/base-mestre/materiais/$id'
    | '/base-mestre/materiais/novo'
    | '/base-mestre/produtos/$id'
    | '/base-mestre/produtos/novo'
    | '/base-mestre/materiais/'
    | '/base-mestre/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asset-center'
    | '/configuracoes'
    | '/importacao'
    | '/launch-control'
    | '/merchandising'
    | '/projeto-inteligente'
    | '/relatorios'
    | '/territory'
    | '/usuarios'
    | '/base-mestre/arquivos'
    | '/base-mestre/categorias'
    | '/base-mestre/compatibilidades'
    | '/base-mestre/familias'
    | '/base-mestre/fornecedores'
    | '/importacao/jbl'
    | '/lancamentos/$id'
    | '/base-mestre'
    | '/lancamentos'
    | '/base-mestre/materiais/$id'
    | '/base-mestre/materiais/novo'
    | '/base-mestre/produtos/$id'
    | '/base-mestre/produtos/novo'
    | '/base-mestre/materiais'
    | '/base-mestre/produtos'
  id:
    | '__root__'
    | '/'
    | '/asset-center'
    | '/base-mestre'
    | '/configuracoes'
    | '/importacao'
    | '/lancamentos'
    | '/launch-control'
    | '/merchandising'
    | '/projeto-inteligente'
    | '/relatorios'
    | '/territory'
    | '/usuarios'
    | '/base-mestre/arquivos'
    | '/base-mestre/categorias'
    | '/base-mestre/compatibilidades'
    | '/base-mestre/familias'
    | '/base-mestre/fornecedores'
    | '/base-mestre/materiais'
    | '/base-mestre/produtos'
    | '/importacao/jbl'
    | '/lancamentos/$id'
    | '/base-mestre/'
    | '/lancamentos/'
    | '/base-mestre/materiais/$id'
    | '/base-mestre/materiais/novo'
    | '/base-mestre/produtos/$id'
    | '/base-mestre/produtos/novo'
    | '/base-mestre/materiais/'
    | '/base-mestre/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetCenterRoute: typeof AssetCenterRoute
  BaseMestreRoute: typeof BaseMestreRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ImportacaoRoute: typeof ImportacaoRouteWithChildren
  LancamentosRoute: typeof LancamentosRouteWithChildren
  LaunchControlRoute: typeof LaunchControlRoute
  MerchandisingRoute: typeof MerchandisingRoute
  ProjetoInteligenteRoute: typeof ProjetoInteligenteRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TerritoryRoute: typeof TerritoryRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territory': {
      id: '/territory'
      path: '/territory'
      fullPath: '/territory'
      preLoaderRoute: typeof TerritoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto-inteligente': {
      id: '/projeto-inteligente'
      path: '/projeto-inteligente'
      fullPath: '/projeto-inteligente'
      preLoaderRoute: typeof ProjetoInteligenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchandising': {
      id: '/merchandising'
      path: '/merchandising'
      fullPath: '/merchandising'
      preLoaderRoute: typeof MerchandisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch-control': {
      id: '/launch-control'
      path: '/launch-control'
      fullPath: '/launch-control'
      preLoaderRoute: typeof LaunchControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacao': {
      id: '/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof ImportacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-mestre': {
      id: '/base-mestre'
      path: '/base-mestre'
      fullPath: '/base-mestre'
      preLoaderRoute: typeof BaseMestreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-center': {
      id: '/asset-center'
      path: '/asset-center'
      fullPath: '/asset-center'
      preLoaderRoute: typeof AssetCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos/': {
      id: '/lancamentos/'
      path: '/'
      fullPath: '/lancamentos/'
      preLoaderRoute: typeof LancamentosIndexRouteImport
      parentRoute: typeof LancamentosRoute
    }
    '/base-mestre/': {
      id: '/base-mestre/'
      path: '/'
      fullPath: '/base-mestre/'
      preLoaderRoute: typeof BaseMestreIndexRouteImport
      parentRoute: typeof BaseMestreRoute
    }
    '/lancamentos/$id': {
      id: '/lancamentos/$id'
      path: '/$id'
      fullPath: '/lancamentos/$id'
      preLoaderRoute: typeof LancamentosIdRouteImport
      parentRoute: typeof LancamentosRoute
    }
    '/importacao/jbl': {
      id: '/importacao/jbl'
      path: '/jbl'
      fullPath: '/importacao/jbl'
      preLoaderRoute: typeof ImportacaoJblRouteImport
      parentRoute: typeof ImportacaoRoute
    }
    '/base-mestre/produtos': {
      id: '/base-mestre/produtos'
      path: '/produtos'
      fullPath: '/base-mestre/produtos'
      preLoaderRoute: typeof BaseMestreProdutosRouteImport
      parentRoute: typeof BaseMestreRoute
    }
    '/base-mestre/materiais': {
      id: '/base-mestre/materiais'
      path: '/materiais'
      fullPath: '/base-mestre/materiais'
      preLoaderRoute: typeof BaseMestreMateriaisRouteImport
      parentRoute: typeof BaseMestreRoute
    }
    '/base-mestre/fornecedores': {
      id: '/base-mestre/fornecedores'
      path: '/fornecedores'
      fullPath: '/base-mestre/fornecedores'
      preLoaderRoute: typeof BaseMestreFornecedoresRouteImport
      parentRoute: typeof BaseMestreRoute
    }
    '/base-mestre/familias': {
      id: '/base-mestre/familias'
      path: '/familias'
      fullPath: '/base-mestre/familias'
      preLoaderRoute: typeof BaseMestreFamiliasRouteImport
      parentRoute: typeof BaseMestreRoute
    }
    '/base-mestre/compatibilidades': {
      id: '/base-mestre/compatibilidades'
      path: '/compatibilidades'
      fullPath: '/base-mestre/compatibilidades'
      preLoaderRoute: typeof BaseMestreCompatibilidadesRouteImport
      parentRoute: typeof BaseMestreRoute
    }
    '/base-mestre/categorias': {
      id: '/base-mestre/categorias'
      path: '/categorias'
      fullPath: '/base-mestre/categorias'
      preLoaderRoute: typeof BaseMestreCategoriasRouteImport
      parentRoute: typeof BaseMestreRoute
    }
    '/base-mestre/arquivos': {
      id: '/base-mestre/arquivos'
      path: '/arquivos'
      fullPath: '/base-mestre/arquivos'
      preLoaderRoute: typeof BaseMestreArquivosRouteImport
      parentRoute: typeof BaseMestreRoute
    }
    '/base-mestre/produtos/': {
      id: '/base-mestre/produtos/'
      path: '/'
      fullPath: '/base-mestre/produtos/'
      preLoaderRoute: typeof BaseMestreProdutosIndexRouteImport
      parentRoute: typeof BaseMestreProdutosRoute
    }
    '/base-mestre/materiais/': {
      id: '/base-mestre/materiais/'
      path: '/'
      fullPath: '/base-mestre/materiais/'
      preLoaderRoute: typeof BaseMestreMateriaisIndexRouteImport
      parentRoute: typeof BaseMestreMateriaisRoute
    }
    '/base-mestre/produtos/novo': {
      id: '/base-mestre/produtos/novo'
      path: '/novo'
      fullPath: '/base-mestre/produtos/novo'
      preLoaderRoute: typeof BaseMestreProdutosNovoRouteImport
      parentRoute: typeof BaseMestreProdutosRoute
    }
    '/base-mestre/produtos/$id': {
      id: '/base-mestre/produtos/$id'
      path: '/$id'
      fullPath: '/base-mestre/produtos/$id'
      preLoaderRoute: typeof BaseMestreProdutosIdRouteImport
      parentRoute: typeof BaseMestreProdutosRoute
    }
    '/base-mestre/materiais/novo': {
      id: '/base-mestre/materiais/novo'
      path: '/novo'
      fullPath: '/base-mestre/materiais/novo'
      preLoaderRoute: typeof BaseMestreMateriaisNovoRouteImport
      parentRoute: typeof BaseMestreMateriaisRoute
    }
    '/base-mestre/materiais/$id': {
      id: '/base-mestre/materiais/$id'
      path: '/$id'
      fullPath: '/base-mestre/materiais/$id'
      preLoaderRoute: typeof BaseMestreMateriaisIdRouteImport
      parentRoute: typeof BaseMestreMateriaisRoute
    }
  }
}

interface BaseMestreMateriaisRouteChildren {
  BaseMestreMateriaisIdRoute: typeof BaseMestreMateriaisIdRoute
  BaseMestreMateriaisNovoRoute: typeof BaseMestreMateriaisNovoRoute
  BaseMestreMateriaisIndexRoute: typeof BaseMestreMateriaisIndexRoute
}

const BaseMestreMateriaisRouteChildren: BaseMestreMateriaisRouteChildren = {
  BaseMestreMateriaisIdRoute: BaseMestreMateriaisIdRoute,
  BaseMestreMateriaisNovoRoute: BaseMestreMateriaisNovoRoute,
  BaseMestreMateriaisIndexRoute: BaseMestreMateriaisIndexRoute,
}

const BaseMestreMateriaisRouteWithChildren =
  BaseMestreMateriaisRoute._addFileChildren(BaseMestreMateriaisRouteChildren)

interface BaseMestreProdutosRouteChildren {
  BaseMestreProdutosIdRoute: typeof BaseMestreProdutosIdRoute
  BaseMestreProdutosNovoRoute: typeof BaseMestreProdutosNovoRoute
  BaseMestreProdutosIndexRoute: typeof BaseMestreProdutosIndexRoute
}

const BaseMestreProdutosRouteChildren: BaseMestreProdutosRouteChildren = {
  BaseMestreProdutosIdRoute: BaseMestreProdutosIdRoute,
  BaseMestreProdutosNovoRoute: BaseMestreProdutosNovoRoute,
  BaseMestreProdutosIndexRoute: BaseMestreProdutosIndexRoute,
}

const BaseMestreProdutosRouteWithChildren =
  BaseMestreProdutosRoute._addFileChildren(BaseMestreProdutosRouteChildren)

interface BaseMestreRouteChildren {
  BaseMestreArquivosRoute: typeof BaseMestreArquivosRoute
  BaseMestreCategoriasRoute: typeof BaseMestreCategoriasRoute
  BaseMestreCompatibilidadesRoute: typeof BaseMestreCompatibilidadesRoute
  BaseMestreFamiliasRoute: typeof BaseMestreFamiliasRoute
  BaseMestreFornecedoresRoute: typeof BaseMestreFornecedoresRoute
  BaseMestreMateriaisRoute: typeof BaseMestreMateriaisRouteWithChildren
  BaseMestreProdutosRoute: typeof BaseMestreProdutosRouteWithChildren
  BaseMestreIndexRoute: typeof BaseMestreIndexRoute
}

const BaseMestreRouteChildren: BaseMestreRouteChildren = {
  BaseMestreArquivosRoute: BaseMestreArquivosRoute,
  BaseMestreCategoriasRoute: BaseMestreCategoriasRoute,
  BaseMestreCompatibilidadesRoute: BaseMestreCompatibilidadesRoute,
  BaseMestreFamiliasRoute: BaseMestreFamiliasRoute,
  BaseMestreFornecedoresRoute: BaseMestreFornecedoresRoute,
  BaseMestreMateriaisRoute: BaseMestreMateriaisRouteWithChildren,
  BaseMestreProdutosRoute: BaseMestreProdutosRouteWithChildren,
  BaseMestreIndexRoute: BaseMestreIndexRoute,
}

const BaseMestreRouteWithChildren = BaseMestreRoute._addFileChildren(
  BaseMestreRouteChildren,
)

interface ImportacaoRouteChildren {
  ImportacaoJblRoute: typeof ImportacaoJblRoute
}

const ImportacaoRouteChildren: ImportacaoRouteChildren = {
  ImportacaoJblRoute: ImportacaoJblRoute,
}

const ImportacaoRouteWithChildren = ImportacaoRoute._addFileChildren(
  ImportacaoRouteChildren,
)

interface LancamentosRouteChildren {
  LancamentosIdRoute: typeof LancamentosIdRoute
  LancamentosIndexRoute: typeof LancamentosIndexRoute
}

const LancamentosRouteChildren: LancamentosRouteChildren = {
  LancamentosIdRoute: LancamentosIdRoute,
  LancamentosIndexRoute: LancamentosIndexRoute,
}

const LancamentosRouteWithChildren = LancamentosRoute._addFileChildren(
  LancamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetCenterRoute: AssetCenterRoute,
  BaseMestreRoute: BaseMestreRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ImportacaoRoute: ImportacaoRouteWithChildren,
  LancamentosRoute: LancamentosRouteWithChildren,
  LaunchControlRoute: LaunchControlRoute,
  MerchandisingRoute: MerchandisingRoute,
  ProjetoInteligenteRoute: ProjetoInteligenteRoute,
  RelatoriosRoute: RelatoriosRoute,
  TerritoryRoute: TerritoryRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
